---
abstract: 'The do-this-then-do-that utility'
author:
  - 'Tomoki Aonuma <uasi@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.57
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.57
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Then
no_index:
  directory:
    - inc
    - t
requires:
  parent: 0
  perl: 5.8.901
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
